#!/usr/bin/env python3
"""
Windows Real-Time Event Log Collector Agent.
Polls System, Application, and Security logs (if accessible) using pywin32,
maps them to the SOC log schema, and sends them to the FastAPI backend.
"""

import socket
import time
import sys
from datetime import datetime, timezone
import requests
import win32evtlog
import win32evtlogutil

BACKEND_URL = "http://127.0.0.1:8000/api/logs/"
POLL_INTERVAL = 5.0  # seconds


class WindowsEventCollector:
    def __init__(self, backend_url: str = BACKEND_URL, poll_interval: float = POLL_INTERVAL):
        self.backend_url = backend_url
        self.poll_interval = poll_interval
        self.log_types = ["System", "Application", "Security"]
        self.last_records = {}
        self.host_name = socket.gethostname() or "local-windows-machine"

    def initialize_tracking(self):
        """Find the newest record number for each log source to avoid sending historical events."""
        print("\n" + "=" * 50)
        print("Initializing Windows Event Tracking Agent")
        print("=" * 50)
        
        for log_type in self.log_types:
            try:
                # Open the event log
                hand = win32evtlog.OpenEventLog(None, log_type)
                
                # Read backwards to get the most recent record number
                flags = win32evtlog.EVENTLOG_BACKWARDS_READ | win32evtlog.EVENTLOG_SEQUENTIAL_READ
                events = win32evtlog.ReadEventLog(hand, flags, 0)
                
                if events:
                    self.last_records[log_type] = events[0].RecordNumber
                else:
                    self.last_records[log_type] = 0
                
                win32evtlog.CloseEventLog(hand)
                print(f"[+] Successfully initialized tracking for [{log_type}] log. Current record: {self.last_records[log_type]}")
            except Exception as e:
                # Security log often requires administrative permissions
                if "Access is denied" in str(e) or log_type == "Security":
                    print(f"[!] Access denied to [{log_type}] log. Run as Administrator if Security events are required. Skipping.")
                else:
                    print(f"[-] Error opening [{log_type}] log: {e}. Skipping.")
                self.last_records[log_type] = None

    def map_severity(self, event_type: int) -> str:
        """Map Windows event severity type integers to SOC severity strings."""
        if event_type == win32evtlog.EVENTLOG_ERROR_TYPE:
            return "high"
        elif event_type == win32evtlog.EVENTLOG_WARNING_TYPE:
            return "warning"
        elif event_type == win32evtlog.EVENTLOG_INFORMATION_TYPE:
            return "info"
        elif event_type == win32evtlog.EVENTLOG_AUDIT_SUCCESS:
            return "info"
        elif event_type == win32evtlog.EVENTLOG_AUDIT_FAILURE:
            return "high"
        else:
            return "info"

    def format_event_message(self, event, log_type: str) -> str:
        """Retrieve the formatted message string. Falls back to string inserts if formatting fails."""
        try:
            msg = win32evtlogutil.SafeFormatMessage(event, log_type)
            if msg:
                return msg.strip()
        except Exception:
            pass

        # Fallback to string inserts if SafeFormatMessage fails
        if event.StringInserts:
            inserts = [str(s) for s in event.StringInserts if s is not None]
            return " | ".join(inserts).strip()

        return f"Windows Event ID {event.EventID} generated by {event.SourceName}"

    def send_to_backend(self, payload: dict) -> bool:
        """Sends the normalized log payload to the FastAPI backend API."""
        try:
            response = requests.post(self.backend_url, json=payload, timeout=5)
            if response.status_code in (200, 201):
                print(f"  [SUCCESS] Sent event: ID {payload['metadata']['event_id']} ({payload['metadata']['log_type']}) - Severity: {payload['severity']}")
                return True
            elif response.status_code == 409:
                data = response.json()
                print(f"  [SKIP] Duplicate event (record_number={payload.get('record_number')}) already stored as log id={data.get('existing_log_id')}. Skipping.")
                # Return True so the collector advances its record pointer and doesn't retry
                return True
            else:
                print(f"  [X] Failed to send event. Status code: {response.status_code}, Response: {response.text}")
                return False
        except requests.exceptions.RequestException as e:
            print(f"  [X] Backend connection error: {e}. Retrying on next poll.")
            return False


    def poll_logs(self):
        """Checks for new events in the active Windows log sources."""
        for log_type in self.log_types:
            last_seen = self.last_records.get(log_type)
            if last_seen is None:
                continue

            try:
                hand = win32evtlog.OpenEventLog(None, log_type)
            except Exception as e:
                # Log may have become inaccessible
                print(f"[!] Warning: Could not open {log_type} log for polling: {e}")
                continue

            new_events = []
            flags = win32evtlog.EVENTLOG_BACKWARDS_READ | win32evtlog.EVENTLOG_SEQUENTIAL_READ

            try:
                # Read the first event backwards to get the most recent record number and detect clearing/rotation
                initial_events = win32evtlog.ReadEventLog(hand, flags, 0)
                if not initial_events:
                    continue

                newest_record = initial_events[0].RecordNumber
                if newest_record < last_seen:
                    print(f"[*] Log [{log_type}] was cleared or rotated. Resetting tracking index from {last_seen} to 0")
                    last_seen = 0
                    self.last_records[log_type] = 0

                # Process the initial batch of events we just read
                stop_reading = False
                for event in initial_events:
                    if event.RecordNumber <= last_seen:
                        stop_reading = True
                        break
                    new_events.append(event)

                # If we haven't hit the last_seen record yet, continue reading backwards
                if not stop_reading:
                    while True:
                        events = win32evtlog.ReadEventLog(hand, flags, 0)
                        if not events:
                            break

                        for event in events:
                            if event.RecordNumber <= last_seen:
                                stop_reading = True
                                break
                            new_events.append(event)

                        if stop_reading:
                            break
            except Exception as e:
                print(f"[-] Error reading events from [{log_type}] log: {e}")
            finally:
                try:
                    win32evtlog.CloseEventLog(hand)
                except Exception:
                    pass

            if new_events:
                # Reverse to process from oldest to newest (chronological order)
                new_events.reverse()
                print(f"[*] Found {len(new_events)} new event(s) in [{log_type}] log.")

                for event in new_events:
                    severity = self.map_severity(event.EventType)
                    message = self.format_event_message(event, log_type)

                    # Convert generate time to ISO 8601 string
                    try:
                        if hasattr(event.TimeGenerated, "astimezone"):
                            timestamp = event.TimeGenerated.astimezone(timezone.utc).isoformat()
                        else:
                            timestamp = event.TimeGenerated.replace(tzinfo=timezone.utc).isoformat()
                    except Exception:
                        timestamp = datetime.now(timezone.utc).isoformat()

                    payload = {
                        "source": "windows-event-viewer",
                        "event_type": "windows_event",
                        "message": message,
                        "severity": severity,
                        "timestamp": timestamp,
                        "host": event.ComputerName or self.host_name,
                        "record_number": event.RecordNumber,
                        "metadata": {
                            "event_id": str(event.EventID),
                            "log_type": log_type,
                            "provider": event.SourceName,
                            "record_number": str(event.RecordNumber)
                        }
                    }

                    if self.send_to_backend(payload):
                        # ONLY update last successfully processed record number upon successful POST
                        self.last_records[log_type] = event.RecordNumber

    def run(self):
        self.initialize_tracking()
        print(f"\n[*] Windows Event Collector Agent is running. Polling every {self.poll_interval}s...")
        try:
            while True:
                self.poll_logs()
                time.sleep(self.poll_interval)
        except KeyboardInterrupt:
            print("\n[!] Agent stopped by user.")


if __name__ == "__main__":
    try:
        collector = WindowsEventCollector()
        collector.run()
    except Exception as exc:
        print(f"[CRITICAL] Collector agent failed to start: {exc}")
        sys.exit(1)
