import { useState } from 'react';
import {
  Box,
  Card,
  CardContent,
  Typography,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  TextField,
  MenuItem,
  Select,
  FormControl,
  InputLabel,
  InputAdornment,
  TablePagination,
  Drawer,
  IconButton,
  Divider,
  Chip,
  Button,
} from '@mui/material';
import {
  Search as SearchIcon,
  NotificationsActive as AlertIcon,
  Warning as CriticalIcon,
  Error as HighIcon,
  FolderOpen as OpenIcon,
  Close as CloseIcon,
  Refresh as RefreshIcon,
} from '@mui/icons-material';

import { useAlerts } from '../../hooks/queries';
import SeverityBadge from '../../components/SeverityBadge';
import StatusChip from '../../components/StatusChip';
import EmptyState from '../../components/EmptyState';
import ErrorState from '../../components/ErrorState';
import LoadingState from '../../components/LoadingState';
import type { AlertRecord } from '../../types';

export default function Alerts() {
  const [severityFilter, setSeverityFilter] = useState<string>('');
  const [statusFilter, setStatusFilter] = useState<string>('');
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [page, setPage] = useState<number>(0);
  const [rowsPerPage, setRowsPerPage] = useState<number>(10);
  const [selectedAlert, setSelectedAlert] = useState<AlertRecord | null>(null);

  const queryParams = {
    severity: severityFilter || undefined,
    status: statusFilter || undefined,
    search: searchQuery || undefined,
    skip: page * rowsPerPage,
    limit: rowsPerPage,
  };

  const { data, isLoading, isError, refetch, isFetching } = useAlerts(queryParams, 10000);

  const alerts = data?.alerts || [];
  const totalCount = data?.total || 0;

  // Stat summary metrics
  const criticalCount = alerts.filter((a) => a.severity?.toLowerCase() === 'critical').length;
  const highCount = alerts.filter((a) => a.severity?.toLowerCase() === 'high').length;
  const openCount = alerts.filter((a) => a.status?.toLowerCase() === 'open').length;

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
      {/* Header Title Bar */}
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Box>
          <Typography variant="h5" sx={{ fontWeight: 800, color: '#0F172A' }}>
            Alerts Dispatch & Monitoring
          </Typography>
          <Typography variant="body2" sx={{ color: '#64748B', mt: 0.5 }}>
            Real-time security alert events generated by the platform correlation engine.
          </Typography>
        </Box>
        <Button
          variant="outlined"
          startIcon={<RefreshIcon className={isFetching ? 'spin' : ''} />}
          onClick={() => refetch()}
          size="small"
          sx={{
            borderColor: '#CBD5E1',
            color: '#334155',
            '&:hover': { borderColor: '#2563EB', backgroundColor: '#EFF6FF' },
          }}
        >
          Refresh Data
        </Button>
      </Box>

      {/* Top Stat Cards */}
      <Box
        sx={{
          display: 'grid',
          gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr', md: 'repeat(4, 1fr)' },
          gap: 2.5,
        }}
      >
        <Card sx={{ borderLeft: '4px solid #2563EB' }}>
          <CardContent sx={{ p: 2.5, '&:last-child': { pb: 2.5 } }}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Box>
                <Typography variant="caption" sx={{ color: '#64748B', fontWeight: 600, textTransform: 'uppercase' }}>
                  Total Alerts (Page)
                </Typography>
                <Typography variant="h4" sx={{ fontWeight: 800, color: '#0F172A', mt: 0.5 }}>
                  {totalCount}
                </Typography>
              </Box>
              <Box sx={{ p: 1.5, borderRadius: '10px', backgroundColor: '#EFF6FF', color: '#2563EB' }}>
                <AlertIcon fontSize="medium" />
              </Box>
            </Box>
          </CardContent>
        </Card>

        <Card sx={{ borderLeft: '4px solid #DC2626' }}>
          <CardContent sx={{ p: 2.5, '&:last-child': { pb: 2.5 } }}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Box>
                <Typography variant="caption" sx={{ color: '#64748B', fontWeight: 600, textTransform: 'uppercase' }}>
                  Critical Severity
                </Typography>
                <Typography variant="h4" sx={{ fontWeight: 800, color: '#DC2626', mt: 0.5 }}>
                  {criticalCount}
                </Typography>
              </Box>
              <Box sx={{ p: 1.5, borderRadius: '10px', backgroundColor: '#FEF2F2', color: '#DC2626' }}>
                <CriticalIcon fontSize="medium" />
              </Box>
            </Box>
          </CardContent>
        </Card>

        <Card sx={{ borderLeft: '4px solid #EA580C' }}>
          <CardContent sx={{ p: 2.5, '&:last-child': { pb: 2.5 } }}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Box>
                <Typography variant="caption" sx={{ color: '#64748B', fontWeight: 600, textTransform: 'uppercase' }}>
                  High Severity
                </Typography>
                <Typography variant="h4" sx={{ fontWeight: 800, color: '#EA580C', mt: 0.5 }}>
                  {highCount}
                </Typography>
              </Box>
              <Box sx={{ p: 1.5, borderRadius: '10px', backgroundColor: '#FFF7ED', color: '#EA580C' }}>
                <HighIcon fontSize="medium" />
              </Box>
            </Box>
          </CardContent>
        </Card>

        <Card sx={{ borderLeft: '4px solid #2563EB' }}>
          <CardContent sx={{ p: 2.5, '&:last-child': { pb: 2.5 } }}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Box>
                <Typography variant="caption" sx={{ color: '#64748B', fontWeight: 600, textTransform: 'uppercase' }}>
                  Open Alerts
                </Typography>
                <Typography variant="h4" sx={{ fontWeight: 800, color: '#2563EB', mt: 0.5 }}>
                  {openCount}
                </Typography>
              </Box>
              <Box sx={{ p: 1.5, borderRadius: '10px', backgroundColor: '#EFF6FF', color: '#2563EB' }}>
                <OpenIcon fontSize="medium" />
              </Box>
            </Box>
          </CardContent>
        </Card>
      </Box>

      {/* Filter and Search Bar */}
      <Card>
        <CardContent sx={{ p: 2, '&:last-child': { pb: 2 } }}>
          <Box
            sx={{
              display: 'flex',
              flexDirection: { xs: 'column', md: 'row' },
              gap: 2,
              alignItems: 'center',
            }}
          >
            {/* Search Input */}
            <Box sx={{ flex: 1, width: '100%' }}>
              <TextField
                fullWidth
                size="small"
                placeholder="Search alert title, IP, host, username, rule..."
                value={searchQuery}
                onChange={(e) => {
                  setSearchQuery(e.target.value);
                  setPage(0);
                }}
                slotProps={{
                  input: {
                    startAdornment: (
                      <InputAdornment position="start">
                        <SearchIcon sx={{ color: '#94A3B8' }} />
                      </InputAdornment>
                    ),
                  },
                }}
              />
            </Box>

            {/* Severity Select */}
            <Box sx={{ width: { xs: '100%', md: 180 } }}>
              <FormControl fullWidth size="small">
                <InputLabel>Severity</InputLabel>
                <Select
                  value={severityFilter}
                  label="Severity"
                  onChange={(e) => {
                    setSeverityFilter(e.target.value);
                    setPage(0);
                  }}
                >
                  <MenuItem value="">All Severities</MenuItem>
                  <MenuItem value="critical">Critical</MenuItem>
                  <MenuItem value="high">High</MenuItem>
                  <MenuItem value="medium">Medium</MenuItem>
                  <MenuItem value="low">Low</MenuItem>
                </Select>
              </FormControl>
            </Box>

            {/* Status Select */}
            <Box sx={{ width: { xs: '100%', md: 180 } }}>
              <FormControl fullWidth size="small">
                <InputLabel>Status</InputLabel>
                <Select
                  value={statusFilter}
                  label="Status"
                  onChange={(e) => {
                    setStatusFilter(e.target.value);
                    setPage(0);
                  }}
                >
                  <MenuItem value="">All Statuses</MenuItem>
                  <MenuItem value="open">Open</MenuItem>
                  <MenuItem value="acknowledged">Acknowledged</MenuItem>
                  <MenuItem value="investigating">Investigating</MenuItem>
                  <MenuItem value="resolved">Resolved</MenuItem>
                  <MenuItem value="closed">Closed</MenuItem>
                </Select>
              </FormControl>
            </Box>

            {/* Clear Filters */}
            {(severityFilter || statusFilter || searchQuery) && (
              <Button
                variant="text"
                size="small"
                onClick={() => {
                  setSeverityFilter('');
                  setStatusFilter('');
                  setSearchQuery('');
                  setPage(0);
                }}
                sx={{ color: '#64748B', whiteSpace: 'nowrap' }}
              >
                Reset
              </Button>
            )}
          </Box>
        </CardContent>
      </Card>

      {/* Main Alerts Table */}
      <TableContainer component={Paper} sx={{ border: '1px solid #E2E8F0', borderRadius: '10px' }}>
        {isLoading ? (
          <LoadingState message="Loading alert records from database..." />
        ) : isError ? (
          <ErrorState message="Failed to load alerts from backend." onRetry={() => refetch()} />
        ) : alerts.length === 0 ? (
          <EmptyState message="No Alerts Found" subMessage="No alerts match the selected criteria or search term." />
        ) : (
          <>
            <Table size="medium">
              <TableHead>
                <TableRow>
                  <TableCell>Alert ID</TableCell>
                  <TableCell>Title</TableCell>
                  <TableCell>Severity</TableCell>
                  <TableCell>Status</TableCell>
                  <TableCell>Source IP</TableCell>
                  <TableCell>Host / Source</TableCell>
                  <TableCell>Count</TableCell>
                  <TableCell>Created At</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {alerts.map((alert) => (
                  <TableRow
                    key={alert.id}
                    onClick={() => setSelectedAlert(alert)}
                    sx={{ cursor: 'pointer' }}
                  >
                    <TableCell sx={{ fontFamily: 'monospace', fontWeight: 700, color: '#2563EB' }}>
                      {alert.alert_id}
                    </TableCell>
                    <TableCell sx={{ fontWeight: 600, color: '#0F172A', maxWidth: 280 }}>
                      {alert.alert_title || 'Untitled Alert'}
                    </TableCell>
                    <TableCell>
                      <SeverityBadge severity={alert.severity || 'low'} />
                    </TableCell>
                    <TableCell>
                      <StatusChip status={alert.status || 'open'} />
                    </TableCell>
                    <TableCell sx={{ fontFamily: 'monospace', color: '#334155' }}>
                      {alert.source_ip || '—'}
                    </TableCell>
                    <TableCell sx={{ color: '#475569' }}>
                      {alert.host || alert.source || '—'}
                    </TableCell>
                    <TableCell sx={{ fontWeight: 700, color: '#0F172A' }}>
                      {alert.occurrence_count || 1}
                    </TableCell>
                    <TableCell sx={{ color: '#64748B', whiteSpace: 'nowrap' }}>
                      {new Date(alert.created_at).toLocaleString()}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>

            <TablePagination
              rowsPerPageOptions={[10, 25, 50]}
              component="div"
              count={totalCount}
              rowsPerPage={rowsPerPage}
              page={page}
              onPageChange={(_, newPage) => setPage(newPage)}
              onRowsPerPageChange={(e) => {
                setRowsPerPage(parseInt(e.target.value, 10));
                setPage(0);
              }}
            />
          </>
        )}
      </TableContainer>

      {/* Alert Detail Side Drawer */}
      <Drawer
        anchor="right"
        open={Boolean(selectedAlert)}
        onClose={() => setSelectedAlert(null)}
        slotProps={{
          paper: {
            sx: { width: { xs: '100%', sm: 460 }, p: 3, backgroundColor: '#FFFFFF' },
          },
        }}
      >
        {selectedAlert && (
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2.5 }}>
            {/* Header */}
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Typography variant="h6" sx={{ fontWeight: 800, color: '#0F172A' }}>
                Alert Details
              </Typography>
              <IconButton onClick={() => setSelectedAlert(null)} size="small">
                <CloseIcon />
              </IconButton>
            </Box>
            <Divider />

            {/* Title & IDs */}
            <Box>
              <Typography variant="caption" sx={{ color: '#64748B', fontWeight: 600 }}>
                ALERT ID
              </Typography>
              <Typography variant="h6" sx={{ fontFamily: 'monospace', color: '#2563EB', fontWeight: 800 }}>
                {selectedAlert.alert_id}
              </Typography>
              <Typography variant="subtitle1" sx={{ fontWeight: 700, mt: 1, color: '#0F172A' }}>
                {selectedAlert.alert_title}
              </Typography>
            </Box>

            {/* Badges */}
            <Box sx={{ display: 'flex', gap: 1.5, alignItems: 'center' }}>
              <SeverityBadge severity={selectedAlert.severity} />
              <StatusChip status={selectedAlert.status} />
              {selectedAlert.risk_score && (
                <Chip
                  label={`Risk Score: ${selectedAlert.risk_score}`}
                  size="small"
                  sx={{ backgroundColor: '#FEF3C7', color: '#92400E', fontWeight: 700 }}
                />
              )}
            </Box>

            <Divider />

            {/* Details Fields */}
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.5 }}>
              <DetailRow label="Source IP" value={selectedAlert.source_ip} isMonospace />
              <DetailRow label="Host Name" value={selectedAlert.host} />
              <DetailRow label="User Name" value={selectedAlert.username} />
              <DetailRow label="Log Source" value={selectedAlert.source} />
              <DetailRow label="Occurrence Count" value={selectedAlert.occurrence_count?.toString()} />
              <DetailRow
                label="First Seen"
                value={selectedAlert.first_seen ? new Date(selectedAlert.first_seen).toLocaleString() : undefined}
              />
              <DetailRow
                label="Last Seen"
                value={selectedAlert.last_seen ? new Date(selectedAlert.last_seen).toLocaleString() : undefined}
              />
              <DetailRow
                label="Created At"
                value={selectedAlert.created_at ? new Date(selectedAlert.created_at).toLocaleString() : undefined}
              />
            </Box>

            {/* Rule Matches */}
            {selectedAlert.rule_matches && (
              <>
                <Divider />
                <Box>
                  <Typography variant="caption" sx={{ color: '#64748B', fontWeight: 700, textTransform: 'uppercase' }}>
                    Triggered Detection Rule
                  </Typography>
                  <Box
                    sx={{
                      p: 1.5,
                      mt: 1,
                      backgroundColor: '#F8FAFC',
                      border: '1px solid #E2E8F0',
                      borderRadius: '6px',
                      fontFamily: 'monospace',
                      fontSize: '0.8rem',
                      color: '#0F172A',
                      wordBreak: 'break-all',
                    }}
                  >
                    {selectedAlert.rule_matches}
                  </Box>
                </Box>
              </>
            )}

            {/* Fingerprints */}
            <Divider />
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
              <Typography variant="caption" sx={{ color: '#64748B', fontWeight: 700, textTransform: 'uppercase' }}>
                Alert Fingerprint
              </Typography>
              <Typography variant="caption" sx={{ fontFamily: 'monospace', color: '#64748B', wordBreak: 'break-all' }}>
                {selectedAlert.alert_fingerprint}
              </Typography>
            </Box>
          </Box>
        )}
      </Drawer>
    </Box>
  );
}

function DetailRow({ label, value, isMonospace = false }: { label: string; value?: string | null; isMonospace?: boolean }) {
  return (
    <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
      <Typography variant="body2" sx={{ color: '#64748B', fontWeight: 500 }}>
        {label}
      </Typography>
      <Typography
        variant="body2"
        sx={{
          color: '#0F172A',
          fontWeight: 600,
          fontFamily: isMonospace ? 'monospace' : 'inherit',
        }}
      >
        {value || '—'}
      </Typography>
    </Box>
  );
}
